### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by MachineGunnur** [jkawamoto/go-pixeldrain#14]
why does it take 14GB+ usage of ram to upload a 5GB file?

**Comment by jkawamoto** [comment]
[The library](https://github.com/go-openapi/runtime) this app uses needs to [copy the uploading file into RAM at least two times](https://github.com/go-openapi/runtime/blob/e518b0a8c812016526404de5f67518865d4e054b/client/request.go#L155-L182) to build a request. That means it'll consume at least 10GB RAM to upload a 5GB file.

Btw, can you upload a 5GB file? [The API document](https://pixeldrain.com/api) looks like the max file size is 1GB:

![スクリーンショット 2021-09-03 3 47 01](https://user-images.githubusercontent.com/1793096/131986292-799f39d0-ee85-42d1-95f7-7892aefcdf02.png)

**Comment by MachineGunnur** [comment]
yes, you can upload 5GB via API. 15GB if you have pro account, etc.

i emailed pixeldrain support and Wim gave me a go app for uploading: https://pixeldrain.com/u/V8UGqPb4
pd "file/location/here"

does not consume ram which is an issue with your app i have as I upload large file simultaneously and i run out of ram.

**Comment by jkawamoto** [comment]
I see. I've just opened a PR https://github.com/go-openapi/runtime/pull/214. It'll reduce the RAM usage.

**Comment by MachineGunnur** [comment]
I see, thank you :)

**Comment by Fornax96** [comment]
Here's the source code for my uploader: https://pixeldrain.com/u/VmcG7r4f

It spawns a separate goroutine to create the multipart file in the background.

**Comment by jkawamoto** [comment]
Thanks for the source code. It looks like [go-openapi/runtime](https://github.com/go-openapi/runtime), which is used in this app, also uses a goroutine to prepare the multipart message:

https://github.com/go-openapi/runtime/blob/2bc043c8ba8a760fd663163517bac1fb69fd717a/client/request.go#L131-L186

It wan't optimal to compute a content type but it's fixed now.
