### ISSUE TITLE
Pd fails to download, with an error that seems like a dns issue

### ISSUE THREAD

**Issue by pitsi** [jkawamoto/go-pixeldrain#16]
Hello!

I discovered your app just yesterday and I gave it a shot. However, it does not work for me and pops an error that looks like a dns issue. In detail, `pd download something` returns this, either with just the id or with the full url
```
./pd download h81i3AGM
 0 B / 74.75 KiB [--------------------------------------------------]   0.00% 0s
Get "https://sia.pixeldrain.com/api/file/h81i3AGM": dial tcp: lookup sia.pixeldrain.com on 8.8.8.8:53: no such host

./pd download https://pixeldrain.com/u/h81i3AGM
 0 B / 74.75 KiB [--------------------------------------------------]   0.00% 0s
Get "https://sia.pixeldrain.com/api/file/h81i3AGM": dial tcp: lookup sia.pixeldrain.com on 8.8.8.8:53: no such host
```
I noticed that `8.8.8.8` there, which is google's dns that I use on my system, so I changed it to something else, e.g. cloudflare's (1.1.1.1) or quad9's (9.9.9.9), but the only thing that changes is that ip and nothing more.

```
./pd download h81i3AGM
 0 B / 74.75 KiB [--------------------------------------------------]   0.00% 0s
Get "https://sia.pixeldrain.com/api/file/h81i3AGM": dial tcp: lookup sia.pixeldrain.com on 1.1.1.1:53: no such host

./pd download h81i3AGM
 0 B / 74.75 KiB [--------------------------------------------------]   0.00% 0s
Get "https://sia.pixeldrain.com/api/file/h81i3AGM": dial tcp: lookup sia.pixeldrain.com on 9.9.9.9:53: no such host
```
Debian testing/unstable x64, pd from the x64 binary (= not the .deb package, I may install it later) from the releases page and the requested file does exist in pixeldrain's site (verified via a browser).
If it helps, I have ipv6 disabled system-wide via a kernel parameter (ipv6.disable=1).

**Comment by pitsi** [comment]
Same thing with the arm64 binary on a tvbox running coreelec (arm64 distro). It definitely has ipv6 enabled, so ipv6 connectivity is not to blame.

**Comment by jkawamoto** [comment]
Thanks for reporting the issue. I didn't know that but they changed download URLs.

[v0.4.2](https://github.com/jkawamoto/go-pixeldrain/releases/tag/v0.4.2) should solve this issue.

**Comment by pitsi** [comment]
It now works on both the amd64 and arm64 systems, so I am closing this.
Thank you very much for the quick reply and the quick fix!
