### ISSUE TITLE
the Linux/arm64 binary is misnamed

### ISSUE THREAD

**Issue by Efreak** [jkawamoto/go-pixeldrain#26]
It's named as an apk file (`pixeldrain_0.5.1_linux_arm64.apk`), but it is not an app. This is a tar.gz.

```
> tar -xzvf pixel*.apk
.PKGINFO
usr/
usr/bin/
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
usr/bin/pd
```
I'm not sure what's up with that APK-TOOLS header, nor why apk tools would be involved in building a command-line app.

Also, the binary inside isn't compatible with android, despite being named a .apk file:
```
❯ usr/bin/pd download https://pixeldrain.com/api/file/something
Get "https://pixeldrain.com/api/file/something/info": dial tcp: lookup pixeldrain.com on [::1]:53: read udp [::1]:47660->[::1]:53: read: connection refused
```
This does run fine under ubuntu proot, though, so I'm guessing this wasn't intended to be run on Android/termux. If you could provide an Android build, that would be helpful (golang is currently unable to build on Android due to missing lock functionality, or I'd build it myself)

**Comment by jkawamoto** [comment]
The apk file isn't for Android but Alpine Linux. I might be able to build a library that can be used from Android apps, but I don't have time to make an Android app.

Btw, I found an Android app https://github.com/wimvdputten/Pixeldrain_android
