### ISSUE TITLE
Problem with deb package: version number doesn't start with a digit

### ISSUE THREAD

**Issue by Fornax96** [jkawamoto/go-pixeldrain#9]
First of all: amazing tool, man. I love it!

There's a problem with your debian installer package 'pd_v0.3.1_amd64.deb'. When I try to install it with `dpkg` it says this:

```
sudo dpkg -i pd_v0.3.1_amd64.deb 
dpkg: error processing archive pd_v0.3.1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 5 package 'pd':
 error in 'Version' field string 'v0.3.1': version number does not start with a digit
Errors were encountered while processing:
 pd_v0.3.1_amd64.deb
```

Your version number cannot start with a `v`

**Comment by jkawamoto** [comment]
Sorry for the late reply. I've just published [v0.4.0](https://github.com/jkawamoto/go-pixeldrain/releases/tag/v0.4.0) that has a correct dep package.
